remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Utkarsh's Git    
description: Hi, my name is Utkarsh Kumar, and I'm a front-end developer with experience in React and Angular. I've developed applications for US clients using Node.js and Spring Boot, and I'm passionate about delivering high-quality products. In my spare time, I'm a freelance 3D modeler and game developer, and I've published several small games on the Play Store.
